"""Add documents table

Revision ID: 1dd6af585968
Revises: fc787215cfcc
Create Date: 2025-09-15 19:04:01.226918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1dd6af585968'
down_revision: Union[str, None] = 'fc787215cfcc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_messages',
    sa.Column('id', sa.String(length=36), nullable=False, comment='消息ID'),
    sa.Column('session_id', sa.String(length=36), nullable=False, comment='会话ID'),
    sa.Column('role', sa.String(length=20), nullable=False, comment='角色：user, assistant, system'),
    sa.Column('content', sa.Text(), nullable=False, comment='消息内容'),
    sa.Column('reasoning', sa.Text(), nullable=True, comment='AI思考过程'),
    sa.Column('message_type', sa.String(length=50), nullable=True, comment='消息类型'),
    sa.Column('knowledge_points', sa.JSON(), nullable=True, comment='关联的知识点数据'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('message_data', sa.JSON(), nullable=True, comment='消息数据'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_sessions',
    sa.Column('id', sa.String(length=36), nullable=False, comment='会话ID'),
    sa.Column('document_id', sa.String(length=36), nullable=False, comment='关联的文档ID'),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'EXPIRED', name='chatsessionstatus'), nullable=True, comment='会话状态'),
    sa.Column('current_knowledge_points', sa.JSON(), nullable=True, comment='当前生成的知识点'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('last_activity', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='最后活动时间'),
    sa.Column('session_data', sa.JSON(), nullable=True, comment='会话数据'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sa.String(length=36), nullable=False, comment='文档ID'),
    sa.Column('filename', sa.String(length=255), nullable=False, comment='文件名'),
    sa.Column('original_filename', sa.String(length=255), nullable=False, comment='原始文件名'),
    sa.Column('file_size', sa.Integer(), nullable=False, comment='文件大小（字节）'),
    sa.Column('file_type', sa.String(length=50), nullable=False, comment='文件类型'),
    sa.Column('extracted_text', sa.Text(), nullable=False, comment='提取的文本内容'),
    sa.Column('text_preview', sa.Text(), nullable=True, comment='文本预览（前2000字符）'),
    sa.Column('status', sa.Enum('UPLOADING', 'PROCESSING', 'COMPLETED', 'FAILED', name='documentstatus'), nullable=True, comment='处理状态'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='错误信息'),
    sa.Column('user_requirements', sa.Text(), nullable=True, comment='用户特殊要求'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.Column('extra_data', sa.JSON(), nullable=True, comment='额外数据'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_table('documents')
    op.drop_table('chat_sessions')
    op.drop_table('chat_messages')
    # ### end Alembic commands ###
